version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunel
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: tcp postgres:5432
    ports:
      - "4040:4040"
    depends_on:
      - postgres